#!/bin/sh -e
#
# 2022 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of the skonfig set __ejabberd.
#
# This set is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This set is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this set. If not, see <http://www.gnu.org/licenses/>.
#
# Prints the current Erlang node name (ERLANG_NODE)
#

erl_quote() {
	printf '%s\n' "$*" | sed -e 's/\\/\\\\/g' -e "s/['\"]/\\\\&/g"
}

mnesia_dir=/var/lib/ejabberd

command -v erl >/dev/null 2>&1 || exit 0
test -d "${mnesia_dir-}" && test -f "${mnesia_dir}/schema.DAT"|| exit 0

# NOTE: catch exception error: undefined function mnesia:system_info/1 in case
#       the data directory exists (backup restore?) but ejabberd has not been
#       installed, yet.
ERL_CRASH_DUMP=/dev/null \
erl -noinput \
	-mnesia dir "\"$(erl_quote "${mnesia_dir}")\"" \
	-eval 'catch io:format("~s~n", [hd(mnesia:system_info(db_nodes))]), halt()'
